server:
  port: 8082
spring:
  datasource:
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/rent_a_car
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: AUTH-SERVICE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
jwt:
  secret: secret
  expirationMs: 86000000
