version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rent_a_car
      - PGDATA=/var/lib/pgsql_docker/data
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: always
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  database-data:
  mongodb_data_container: