server:
  port: 9098
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/user
#            - Header=X-User-Id
#          filters:
#            - AuthenticationPrefilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/signin
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/signup
#        - id: AUTH-SERVICE
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/api/auth/validateToken
#            - Header=Authorization
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/test/user
          filters:
            - AuthenticationPrefilter
        - id: ADS-PLACEMENT-SERVICE
          uri: lb://ADS-PLACEMENT-SERVICE
          predicates:
            - Path=/ads
#          filters:
#            - AuthenticationPrefilter
        - id: CAR-SERVICE
          uri: lb://CAR-SERVICE
          predicates:
            - Path=/cars
#          filters:
#            - AuthenticationPrefilter
    discovery:
      enabled: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
